name: pipeline-basico
on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executa comando
        run: echo "Configuração inicial do pipeline"
        - name: Esperar Aprovação
        run: echo "Aguardando aprovação..."
        if: github.event_name == 'workflow_dispatch'
